const problems = [
  {id:"PEPG-0001",title:"Centralized governance and concentration of execution and oversight",short:"A governance problem in which excessive centralization can reduce distributed participation and concentrate implementation and oversight.",definition:"Government capacity can become highly centralized, while execution and oversight may be concentrated in limited institutional channels. This can slow problem-solving, reduce public participation, and create risks of institutional or operational monopoly.",status:"community",statusLabel:"Community verified",proposer:"Milad Habibpour",solutionProposer:"Milad Habibpour",solution:"Platform-Enabled People Governance (PEPG)",verification:"Community confirmation in this prototype. A future PEPG Board may allow a trusted authority to verify the problem.",evidence:"Prototype record — evidence and verification workflow are illustrative.",votes:{up:18,down:3},definitionProposals:[{type:"Improved definition",text:"Separate administrative centralization from monopoly in implementation and oversight.",votes:{up:9,down:1}},{type:"Sub-problem",text:"Concentration of oversight functions.",votes:{up:7,down:1}},{type:"Separate problem",text:"Slow coordination of large public projects.",votes:{up:5,down:2}},{type:"Not correctly defined",text:"The current definition may combine several distinct governance problems and should be narrowed.",votes:{up:3,down:1}}],links:{solution:"https://doi.org/10.5281/zenodo.22133939",solutionsGroup:"https://t.me/pepg_solutions_example",implementation:"https://github.com/miladhp94/pepg",oversight:"https://example.org/pepg/oversight/0001",reports:"https://example.org/pepg/reports/0001"}},
  {id:"PEPG-0002",title:"Poor asphalt quality on an Abstract Street in Tanzania",short:"An illustrative public infrastructure problem showing how one problem can connect evidence, solutions, funding, implementation and oversight.",definition:"The asphalt surface on an Abstract Street in Tanzania is reported to deteriorate prematurely, creating mobility, safety, maintenance and public-resource concerns.",status:"authority",statusLabel:"Authority verified",proposer:"Community Problem Reporter",solutionProposer:"Milad Habibpour",solution:"PEPG-based distributed problem-solving workflow",verification:"Illustrative authority verification by a local public works authority. This is prototype data.",evidence:"Illustrative inspection report and community evidence.",votes:{up:27,down:4},definitionProposals:[{type:"Sub-problem",text:"Drainage failure contributing to pavement deterioration.",votes:{up:12,down:1}},{type:"Improved definition",text:"Specify pavement age, road segment, material specification and failure pattern.",votes:{up:16,down:2}},{type:"Separate problem",text:"Unsafe pedestrian access caused by road-surface failure.",votes:{up:8,down:1}},{type:"Not correctly defined",text:"The problem needs a precise road segment and measurable definition before intervention.",votes:{up:4,down:1}}],links:{solution:"https://doi.org/10.5281/zenodo.22133939",solutionsGroup:"https://t.me/pepg_solutions_example_0002",funding:"https://example.org/pepg/funding/0002",implementation:"https://example.org/pepg/implementation/0002",oversight:"https://example.org/pepg/oversight/0002",reports:"https://example.org/pepg/reports/0002"}}
];


// Prototype state: keep user actions during the current browser session.
problems.forEach(p=>{
  p.votes=p.votes||{up:0,down:0};
  p.definitionProposals=p.definitionProposals||[];
  p.solutionProposals=p.solutionProposals||[];
  p.verificationRequests=p.verificationRequests||0;
  p.joinRequests=p.joinRequests||{};
});

const grid=document.getElementById("problemGrid"),search=document.getElementById("search"),statusFilter=document.getElementById("statusFilter"),problemModal=document.getElementById("problemModal"),submitModal=document.getElementById("submitModal"),detail=document.getElementById("problemDetail");
const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
function render(){const q=search.value.trim().toLowerCase(),s=statusFilter.value,f=problems.filter(p=>([p.id,p.title,p.short,p.definition].join(" ").toLowerCase().includes(q))&&(s==="all"||p.status===s));grid.innerHTML=f.length?f.map(p=>`<article class="problem-card" data-id="${p.id}"><div class="problem-id">${p.id}</div><h3>${esc(p.title)}</h3><p>${esc(p.short)}</p><div class="tags"><span class="tag ${p.status==="authority"?"verified":"community"}">${p.statusLabel}</span><span class="tag">Problem definition</span><span class="tag">Community actions</span></div></article>`).join(""):"<div class='empty'>No problems match your search.</div>";document.querySelectorAll(".problem-card").forEach(c=>c.onclick=()=>openProblem(c.dataset.id))}

function proposalCard(p,index){const x=p.definitionProposals[index];return `<div class="proposal-card"><div class="proposal-top"><span class="tag">${esc(x.type)}</span><span class="proposal-index">Proposal ${index+1}</span></div><p>${esc(x.text)}</p><div class="proposal-actions"><button class="mini-button" onclick="voteProposal('${p.id}',${index},'up')">▲ ${x.votes.up} Agree</button><button class="mini-button" onclick="voteProposal('${p.id}',${index},'down')">▼ ${x.votes.down} Disagree</button><button class="mini-button" onclick="supportProposal('${p.id}',${index})">Support</button></div></div>`}

function openProblem(id){const p=problems.find(x=>x.id===id);if(!p)return;p.votes=p.votes||{up:0,down:0};p.definitionProposals=p.definitionProposals||[];const links=Object.entries(p.links||{}).map(([k,u])=>`<a href="${u}" target="_blank" rel="noopener">${k.replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase())}</a>`).join(" · ");detail.innerHTML=`
<div class="detail-head"><div class="problem-id">${p.id}</div><h2>${esc(p.title)}</h2><div class="tags"><span class="tag ${p.status==="authority"?"verified":"community"}">${p.statusLabel}</span><span class="tag">Open for participation</span></div></div>
<div class="detail-grid">
<div class="detail-box full"><h4>Problem definition</h4><p>${esc(p.definition)}</p><div class="join-row"><button class="button secondary" onclick="redefineProblem('${p.id}')">↻ Propose a new definition</button><button class="button secondary" onclick="markProblem('${p.id}','unclear')">Flag as unclear</button></div><p class="notice">A proposed definition does not silently replace the current definition. It becomes a proposal and can be reviewed and voted on.</p></div>
<div class="detail-box"><h4>Problem proposer</h4><p>${esc(p.proposer)}</p></div><div class="detail-box"><h4>Verification</h4><p>${esc(p.verification)}</p><div class="join-row"><button class="button secondary" onclick="verifyProblem('${p.id}')">Request verification</button></div><p class="notice">Requests: ${p.verificationRequests||0}</p></div>
<div class="detail-box full"><h4>Solution</h4><p><strong>${esc(p.solution)}</strong></p><p class="notice">Solutions may live outside the Board. The Board keeps the common Problem ID and links the activity.</p><div class="join-row"><a class="button primary" href="${p.links.solution||'#'}" target="_blank" rel="noopener">Read solution / paper</a>${p.links.solutionsGroup?`<a class="button secondary" href="${p.links.solutionsGroup}" target="_blank" rel="noopener">Join solution group</a>`:""}<button class="button secondary" onclick="suggestSolution('${p.id}')">+ Suggest a solution</button></div><p class="notice">Solution proposer: ${esc(p.solutionProposer)}</p>${p.solutionProposals.length?`<div class="proposal-list"><strong>Community solution proposals</strong>${p.solutionProposals.map((x,i)=>`<div class="proposal-card"><div class="proposal-top"><span class="tag">Solution</span><span class="proposal-index">Proposal ${i+1}</span></div><p>${esc(x.title)}</p>${x.link?`<p><a href="${esc(x.link)}" target="_blank" rel="noopener">Open external solution</a></p>`:""}<div class="proposal-actions"><button class="mini-button" onclick="voteSolution('${p.id}',${i},'up')">▲ ${x.votes.up} Agree</button><button class="mini-button" onclick="voteSolution('${p.id}',${i},'down')">▼ ${x.votes.down} Disagree</button></div></div>`).join("")}</div>`:""}</div>
<div class="detail-box full"><h4>Community validation</h4><p class="muted">Every problem can be confirmed or challenged. These votes help the Board distinguish a supported problem from a disputed one.</p><div class="action-grid compact"><button class="action-card vote-up" onclick="voteProblem('${p.id}','up')"><span class="action-icon">▲</span><strong>Confirm / agree</strong><small>${p.votes.up} community confirmations</small></button><button class="action-card vote-down" onclick="voteProblem('${p.id}','down')"><span class="action-icon">▼</span><strong>Reject / disagree</strong><small>${p.votes.down} community objections</small></button></div></div>
<div class="detail-box full"><h4>Definition proposals</h4><p class="muted">Users can classify a contribution as an improved definition, a sub-problem, a separate problem, or a claim that the problem is not correctly defined.</p><div class="proposal-list">${p.definitionProposals.length?p.definitionProposals.map((_,i)=>proposalCard(p,i)).join(""):"<div class='empty'>No proposals yet.</div>"}</div><div class="join-row"><button class="button secondary" onclick="redefineProblem('${p.id}')">+ Propose an improved definition</button><button class="button secondary" onclick="createSubproblem('${p.id}')">+ Add a sub-problem</button><button class="button secondary" onclick="createSeparateProblem('${p.id}')">+ Suggest separate problem</button><button class="button secondary" onclick="challengeDefinition('${p.id}')">! Say not correctly defined</button></div><p class="notice">In the production system, proposal history would remain visible and acceptance rules would determine when a new definition becomes the active definition.</p></div>
<div class="detail-box"><h4>Evidence</h4><p>${esc(p.evidence)}</p></div><div class="detail-box"><h4>External links</h4><p>${links||"No links yet."}</p></div>
<div class="detail-box full"><h4>Funding · Implementation · Oversight · Reports</h4><p>PEPG Board can link specialized activity hosted elsewhere. Joining implementation or oversight may require approval by the responsible authority.</p><div class="join-row">${p.links.funding?`<a class="button secondary" href="${p.links.funding}" target="_blank">Funding</a>`:""}${p.links.implementation?`<button class="button secondary" onclick="requestJoin('implementation','${p.id}')">Request to join implementation${p.joinRequests?.implementation?` (${p.joinRequests.implementation})`:""}</button>`:""}${p.links.oversight?`<button class="button secondary" onclick="requestJoin('oversight','${p.id}')">Request to join oversight${p.joinRequests?.oversight?` (${p.joinRequests.oversight})`:""}</button>`:""}${p.links.reports?`<a class="button secondary" href="${p.links.reports}" target="_blank">Reports</a>`:""}</div><p class="notice">Prototype only: these links and approvals are illustrative. The Board can remain platform-independent while preserving the common Problem ID.</p></div>
</div>`;problemModal.classList.add("open");problemModal.setAttribute("aria-hidden","false")}

function redefineProblem(id){const p=problems.find(x=>x.id===id);if(!p)return;const proposal=prompt("Write an improved definition for this problem:");if(!proposal||!proposal.trim())return;p.definitionProposals.push({type:"Improved definition",text:proposal.trim(),votes:{up:0,down:0}});openProblem(id)}
function createSubproblem(id){const p=problems.find(x=>x.id===id);if(!p)return;const title=prompt("Title of the sub-problem:");if(!title||!title.trim())return;const definition=prompt("Define the sub-problem:");if(!definition||!definition.trim())return;createProblem({title:title.trim(),definition:definition.trim(),parentProblem:p.id});alert("Sub-problem created in the prototype.")}
function createSeparateProblem(id){const p=problems.find(x=>x.id===id);if(!p)return;const title=prompt("Title of the separate problem:");if(!title||!title.trim())return;const definition=prompt("Define the separate problem:");if(!definition||!definition.trim())return;createProblem({title:title.trim(),definition:definition.trim(),relatedProblem:p.id});alert("Separate problem created in the prototype.")}
function challengeDefinition(id){const p=problems.find(x=>x.id===id);if(!p)return;const reason=prompt("Why is the current problem definition not correct or sufficiently precise?");if(!reason||!reason.trim())return;p.definitionProposals.push({type:"Not correctly defined",text:reason.trim(),votes:{up:0,down:0}});openProblem(id)}
function voteProblem(id,d){const p=problems.find(x=>x.id===id);if(!p)return;p.votes=p.votes||{up:0,down:0};p.votes[d]++;openProblem(id)}
function voteProposal(id,index,d){const p=problems.find(x=>x.id===id),x=p&&p.definitionProposals[index];if(!x)return;x.votes=x.votes||{up:0,down:0};x.votes[d]++;openProblem(id)}
function voteSolution(id,index,d){const p=problems.find(x=>x.id===id),x=p&&p.solutionProposals[index];if(!x)return;x.votes=x.votes||{up:0,down:0};x.votes[d]++;openProblem(id)}
function supportProposal(id,index){
  const p=problems.find(x=>x.id===id),x=p&&p.definitionProposals[index];
  if(!x)return;
  x.supports=(x.supports||0)+1;
  openProblem(id);
}
function suggestSolution(id){
  const p=problems.find(x=>x.id===id);
  if(!p)return;
  const title=prompt("Solution title:");
  if(!title||!title.trim())return;
  const link=prompt("Optional external link (URL):","");
  p.solutionProposals.push({title:title.trim(),link:(link||"").trim(),proposer:"Community user",votes:{up:0,down:0}});
  openProblem(id);
}
function markProblem(id,type){
  const p=problems.find(x=>x.id===id);
  if(!p)return;
  const reason=prompt("Explain why the current problem definition is unclear or incorrect:");
  if(!reason||!reason.trim())return;
  p.definitionProposals.push({type:"Not correctly defined",text:reason.trim(),votes:{up:0,down:0},supports:0});
  openProblem(id);
}
function verifyProblem(id){
  const p=problems.find(x=>x.id===id);
  if(!p)return;
  p.verificationRequests=(p.verificationRequests||0)+1;
  p.verification=`Verification requested by ${p.verificationRequests} user(s). A trusted authority or community reviewers can process the request.`;
  openProblem(id);
}
function requestJoin(area,id){
  const p=problems.find(x=>x.id===id);
  if(!p)return;
  p.joinRequests=p.joinRequests||{};
  p.joinRequests[area]=(p.joinRequests[area]||0)+1;
  openProblem(id);
}
function createProblem(data){const next=`PEPG-${String(problems.length+1).padStart(4,"0")}`;problems.push({id:next,title:data.title,short:data.definition.slice(0,150),definition:data.definition,status:"unverified",statusLabel:"Unverified",proposer:"Community user",solutionProposer:"Not defined",solution:"No solution linked yet",verification:"Not yet verified.",evidence:"Created in the prototype.",votes:{up:0,down:0},definitionProposals:[],links:{},parentProblem:data.parentProblem,relatedProblem:data.relatedProblem});openProblem(next)}

search.oninput=render;statusFilter.onchange=render;document.getElementById("openSubmit").onclick=()=>{submitModal.classList.add("open");submitModal.setAttribute("aria-hidden","false")};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>{const e=document.getElementById(b.dataset.close);e.classList.remove("open");e.setAttribute("aria-hidden","true")});[problemModal,submitModal].forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove("open")});
document.getElementById("submitForm").onsubmit=e=>{e.preventDefault();const title=document.getElementById("newTitle").value.trim(),definition=document.getElementById("newDefinition").value.trim(),author=document.getElementById("newAuthor").value.trim();const next=`PEPG-${String(problems.length+1).padStart(4,"0")}`;problems.push({id:next,title,short:definition.slice(0,150)+(definition.length>150?"…":""),definition,status:"unverified",statusLabel:"Unverified",proposer:author,solutionProposer:"Not defined",solution:"No solution linked yet",verification:"Not yet verified.",evidence:"Submitted through the prototype.",votes:{up:0,down:0},definitionProposals:[],links:{}});e.target.reset();submitModal.classList.remove("open");render();alert(`${next} created in the prototype. It is stored only in this browser session.`)};render();
